# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/Maciek
Accept: application/json

###

GET http://127.0.0.1:8000/sum?x=5&y=15
Accept: application/json

###

GET http://127.0.0.1:8000/geocode
Accept: application/json

###

GET http://127.0.0.1:8000/geocode?lat=50.0680275&lon=19.9098668
Accept: application/json

###

GET http://127.0.0.1:8000/movies
Accept: application/json

###

GET http://127.0.0.1:8000/movies/1
Accept: application/json

###

POST http://127.0.0.1:8000/movies
Content-Type: application/json

{
  "title": "Inception",
  "year": 2010,
  "actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page"
}

> {%
    client.global.set("created_movie_id", response.body.movie_id);
%}

###

DELETE http://127.0.0.1:8000/movies/{{created_movie_id}}
Accept: application/json

###

PUT http://127.0.0.1:8000/movies/{{created_movie_id}}
Content-Type: application/json

{
  "title": "Inception - Updated",
  "year": 2010,
  "actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy"
}

###

DELETE http://127.0.0.1:8000/movies
Content-Type: application/json

[1, 2, 3]


###

GET http://127.0.0.1:8000/orm/movies
Accept: application/json

###

GET http://127.0.0.1:8000/orm/actors
Accept: application/json

